// Code generated by "stringer -type=Dof"; DO NOT EDIT.

package deflect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ux-0]
	_ = x[Uz-1]
	_ = x[Uy-2]
	_ = x[Phiy-3]
	_ = x[Phiz-4]
	_ = x[Phix-5]
}

const _Dof_name = "UxUzUyPhiyPhizPhix"

var _Dof_index = [...]uint8{0, 2, 4, 6, 10, 14, 18}

func (i Dof) String() string {
	if i >= Dof(len(_Dof_index)-1) {
		return "Dof(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Dof_name[_Dof_index[i]:_Dof_index[i+1]]
}
