// Code generated by "stringer -type=Fct -trimprefix Fct"; DO NOT EDIT.

package deflect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FctUnknown-0]
	_ = x[FctUx-1]
	_ = x[FctUz-2]
	_ = x[FctUy-3]
	_ = x[FctPhiy-4]
	_ = x[FctPhiz-5]
	_ = x[FctPhix-6]
	_ = x[FctNx-7]
	_ = x[FctVz-8]
	_ = x[FctVy-9]
	_ = x[FctMy-10]
	_ = x[FctMz-11]
	_ = x[FctMx-12]
}

const _Fct_name = "UnknownUxUzUyPhiyPhizPhixNxVzVyMyMzMx"

var _Fct_index = [...]uint8{0, 7, 9, 11, 13, 17, 21, 25, 27, 29, 31, 33, 35, 37}

func (i Fct) String() string {
	if i >= Fct(len(_Fct_index)-1) {
		return "Fct(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Fct_name[_Fct_index[i]:_Fct_index[i+1]]
}
