default_language_version:
    python: python3.12
    golang: 1.22.0

repos:
  - repo: https://github.com/segmentio/golines
    rev: v0.12.2
    hooks:
      - id: golines
        args: [-m, '100', -t, '2']
  - repo: https://github.com/lubgr/go-hooks
    rev: v0.1.1
    hooks:
      - id: goimports
      - id: build
        fail_fast: true
      - id: test
        args: [-parallel, '8', ./...]
      - id: vet
      - id: mod-tidy
      - id: staticcheck
      - id: errcheck
        args: [-ignoretests, -blank, ./...]
      - id: godot
      - id: revive
        args: [-config, .revive-config.toml, ./...]
      - id: go-critic
        args: [check,
          '-enable=#diagnostic,#performance,#style,emptyStringTest',
          '-disable=unnamedResult',
          ./...]
      - id: errname
        language_version: 1.21.8
      - id: ineffassign
  - repo: https://github.com/google/go-jsonnet
    rev: v0.20.0
    hooks:
      - id: jsonnet-format
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix, 'lf']
      - id: trailing-whitespace
